### ISSUE TITLE
Register to bower repository

### ISSUE THREAD

**Issue by tomalec** [Palindrom/puppet-client#3]
`puppet-js` is registered and `puppet-client` is not.

I think we should remove and unregister `puppet-js` complately and register `puppet-client`.
Or maybe we should keep `puppet-js` as `puppet-client` version without Starcounter's our opinionated setup?

**Comment by warpech** [comment]
Closing as this repo is no longer maintained

**Comment by tomalec** [comment]
@warpech, @alshakero  Maybe we should remove it then, not to introduce confusion. Unless, we could soon use it again for React, Vue integration

**Comment by warpech** [comment]
Or just rename it to `puppet-client-old`

**Comment by tomalec** [comment]
or leave it as `puppet-client` and not rename to Palindrom?
